### ISSUE TITLE
Outdated Issues

### ISSUE THREAD

**Issue by i10416** [typelevel/spire#1102]
These issues seem outdated.

- https://github.com/typelevel/spire/issues/194 we have jmh benchmarks for `Rational` and `SafeLong`
- https://github.com/typelevel/spire/issues/563 we now check docs with mdoc
- https://github.com/typelevel/spire/issues/702 we now check docs with mdoc
- https://github.com/typelevel/spire/issues/315 Docsite has guide and design sections.
- https://github.com/typelevel/spire/issues/516  : change log for v0.16.1-SNAPSHOT says "disabled benchmarked depending on Caliper"
- https://github.com/typelevel/spire/issues/818 fixed by https://github.com/typelevel/spire/commit/8989a66434288cc9daac8fa6cce35eb20f1cfa92

**Comment by armanbilge** [comment]
Thanks, very helpful!

I'm leaving a few open:
- #194: I think that issue is pointing out not that benhmarks are _missing_ for `Rational` and `SafeLong` but that they are not sophisticated/realistic
- #701: provides an outline for the microsite of which seems like still lots to be done
- #315: the guide on the site is a user guide, not a developer style guide. The design notes also seems more focused on implementation details rather than overall style.
