### ISSUE TITLE
Ensure Javadoc comments for all non-trivial (*) methods

### ISSUE THREAD

**Issue by non** [typelevel/spire#193]
Trivial methods would include things like:

``` scala
def +(rhs: X): X = lhs.x + rhs.x
```

Javadoc comments should be written as:

``` scala
/**
 * This is a method that does something useful.
 */
```

**Comment by kschwarz1116** [comment]
Might be good to add this to [CONTRIBUTING.md](https://github.com/typelevel/spire/blob/38f4fcd96cda50839754dee4fdc802329c23edc6/CONTRIBUTING.md#submitting-patches-or-code) as a style-point. This seems like something that should happen continuously rather than being able to say that it's explicitly done forever.

**Comment by armanbilge** [comment]
Agree. Broad issues are difficult to close once-and-for-all but don't point to specific, actionable tasks.
