### ISSUE TITLE
workaround needed for Scala 2.13.0-RC1

### ISSUE THREAD

**Issue by SethTisue** [typelevel/spire#788]
see @adriaanm's changes at https://github.com/scalacommunitybuild/spire/commit/366f435d00749eb0955073916660d063cc0ae554

**Comment by larsrh** [comment]
This is only a WIP that AFAICT will crash at runtime. Not sure yet how to fix this.

**Comment by szeiger** [comment]
How is this code tested? `spireJVM/test` passes on RC1 directly from master without Adriaan's patch (using Machinist 0.6.7) and `examples/test` does something ("Generating spire/std/tuples.scala") that isn't obvious from the build description, but it doesn't contain any tests.

**Comment by dwijnand** [comment]
Try `validateJVM`.

**Comment by szeiger** [comment]
`validateJVM` doesn't do much more. All test in there are passing. The sbt build isn't designed to deal with different dependencies for diffrerent target versions so it will require some refactoring for cross-building but other than that I see no issues with RC1.

**Comment by szeiger** [comment]
Oh, looks like I somehow reset the Scala version again so I wasn't testing on RC1. And there's no version of `algebra` yet for RC1 (or any other 2.13 build), so I'll have to start with that.

**Comment by szeiger** [comment]
Here's a fix for the sample code for completeness (not actually needed by this example): https://github.com/scalacommunitybuild/spire/commit/1037e5cec3bf70c0a6154ca5dab7bd4dcaab394d

I gave up trying to run the test suite on a "proper" build of Spire using published versions of the dependencies outside of the community build because the changes in ScalaTest and/or scalacheck result in hundreds of compile errors.

**Comment by larsrh** [comment]
Closed by #796.
