### ISSUE TITLE
Dotty compatibility

### ISSUE THREAD

**Issue by larsrh** [typelevel/spire#936]
This likely requires a ton of work.

~For starters, typelevel/cats#2041 needs to be done first.~

**Comment by cquiroz** [comment]
I'd be interested to tackle this one. Can we get an algebra release with Dotty support?

**Comment by larsrh** [comment]
2.1.0 is out

**Comment by cquiroz** [comment]
Thanks

**Comment by cquiroz** [comment]
I started cracking at this and it's going to be quite a bit of changes given the amount of macros.

One of the first things I'd like to do is to get rid of all warnings and move to `munit`

Could I drop support for 2.12 to make the conversion to dotty easier, it would let me get rid of most warnings and `scala-collection-compat`

**Comment by larsrh** [comment]
Fine with me, I'd say.

**Comment by cquiroz** [comment]
I'm still doing some progress with this. A difficulty is the amount of macros spire has so a first round of a port will only do macros where strictly necessary. In cases where a macro is only done for performance reason it will be done later.

One of the macros that seem to need to be ported is `Checked`
https://github.com/typelevel/spire/blob/master/macros/src/main/scala/spire/macros/Checked.scala#L170

If you think not please let me know and how should I replace it

Note that this bug was a showstopper but it has been fixed upstream
https://github.com/lampepfl/dotty/issues/12708

**Comment by SethTisue** [comment]
not sure if @bishabosha's https://github.com/bishabosha/spire-scala3 has anything useful here — perhaps you've already surpassed it

**Comment by cquiroz** [comment]
Thanks for the tip. I managed to compile core but still have troubles porting some of the macros

We'd need to make sure the tests run too

**Comment by som-snytt** [comment]
> This likely requires a ton of work.

Is it a metric ton or the other kind? tonne?

**Comment by cquiroz** [comment]
Got the `Checked.scala` macro ported. This lets me know fully compile `core` in scala 3. 
I'm not very familiar with macros but tests are passing. I'd appreciate feedback if you want to take a look

https://gist.github.com/cquiroz/8c6825aae439230f2850fc2eb93410d0

**Comment by armanbilge** [comment]
https://github.com/typelevel/spire/pull/1067.
